<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="INVENGER-819" failures="1" tests="2" name="CarLoan" time="0.025" errors="0" timestamp="2024-04-04T11:20:06 IST">
  <testcase classname="test.day3" name="APILogin" time="0.002"/>
  <testcase classname="test.day3" name="WebLogin" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day3.WebLogin(day3.java:18)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- WebLogin -->
  <testcase classname="test.day3" name="MobileSigout" time="0.0">
    <ignored/>
  </testcase> <!-- MobileSigout -->
  <testcase classname="test.day3" name="MobileLogin" time="0.0">
    <ignored/>
  </testcase> <!-- MobileLogin -->
  <testcase classname="test.day3" name="MobileDashboard" time="0.0">
    <ignored/>
  </testcase> <!-- MobileDashboard -->
</testsuite> <!-- CarLoan -->
